apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-pipeline
  template:
    metadata:
      labels:
        app: ml-pipeline
    spec:
      containers:
      - name: ml-pipeline
        image: ml-pipeline:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline-service
spec:
  type: LoadBalancer
  selector:
    app: ml-pipeline
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
