pipeline {
    agent any
    tools {
        'jenkins.plugins.shiningpanda.tools.PythonInstallation'Python3.8'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/skalokhe/ML-DevOps-Pipeline.git'
            }
        }
        stage('Setup Python')
        {
            steps{
                sh '''
                python --version
                pip --version
                '''
            }
        }
        stage('Install Dependencies') {
            steps {
                sh '''
                /usr/local/bin/python3 -m venv venv
                . venv/bin/activate
                ./venv/bin/pip install --upgrade pip
                ./venv/bin/pip install -r requirements.txt
                '''
            }
        }
        stage('Test') {
            steps {
                sh 'pytest'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ml-pipeline:latest .'
            }
        }
        stage('Push Docker Image') {
            steps {
                withCredentials([string(credentialsId: 'docker-hub-password', variable: 'DOCKER_PASSWORD')]) {
                    sh 'echo $DOCKER_PASSWORD | docker login -u your-dockerhub-username --password-stdin'
                    sh 'docker push ml-pipeline:latest'
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f docker/kubernetes/deployment.yml'
            }
        }
    }
}
